# Generated by Django 4.2.7 on 2024-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricing_plan_name", models.CharField(max_length=100)),
                ("pricing_plan_adv", models.CharField(max_length=100)),
                ("pricing_plan_price", models.CharField(max_length=100)),
                ("pricing_plan_creator", models.CharField(max_length=100)),
            ],
        ),
    ]
