# Generated by Django 4.2.7 on 2024-04-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_ms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingplan",
            old_name="pricing_plan_adv",
            new_name="adv",
        ),
        migrations.RenameField(
            model_name="pricingplan",
            old_name="pricing_plan_creator",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="pricingplan",
            old_name="pricing_plan_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="pricingplan",
            old_name="pricing_plan_price",
            new_name="price",
        ),
    ]
