# Generated by Django 4.2.7 on 2024-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_ms", "0002_rename_pricing_plan_adv_pricingplan_adv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
