# Generated by Django 4.2.7 on 2024-04-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_ms", "0003_alter_pricingplan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingBalance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("balance", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.CharField(max_length=100)),
                ("userId", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
