# Generated by Django 4.2.7 on 2024-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_ms", "0004_accountingbalance_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingbalance",
            name="balance",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
